## Colors configuration
[colors.primary]
background = "#000000"
foreground = "#eeffff"

[colors.normal]
black   = "#263238"
red     = "#f07178"
green   = "#c3e88d"
yellow  = "#ffcb6b"
blue    = "#82aaff"
magenta = "#c792ea"
cyan    = "#89ddff"
white   = "#eeffff"

[colors.bright]
black   = "#263238"
red     = "#f07178"
green   = "#c3e88d"
yellow  = "#ffcb6b"
blue    = "#82aaff"
magenta = "#c792ea"
cyan    = "#89ddff"
white   = "#ffffff"
